name: practice build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DockerImage: my-bday
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: checking docker info
        run: docker info
      - name: docker images
        run: docker images
      - name: remove docker image and all existing containers
        run: docker rmi -f $(docker images -q) || true && docker rm -f $(docker ps -aq) || true
      - name: Build Docker image
        run: docker build -t ${{ env.DockerImage }} .
      - name: docker tag
        run: docker tag ${{ env.DockerImage }} ${{ secrets.DOCKER_USERNAME }}/${{ env.DockerImage }}:${{ github.sha }}
      - name: push to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.DockerImage }}:${{ github.sha }}
      - name: Update Kubernetes manifest
        run: |
          sed -i "s|image:.*|image: mydockerhubuser/myapp:${{ github.sha }}|" k8s/deployment.yaml
      - name: Commit changes
        run: |
          git add k8s/deployment.yaml
          git commit -m "Update image"
          git push
      